#!/bin/sh

set -e -x

lein run -m fantasy-football-2015.cbs-downloader
lein run -m fantasy-football-2015.espn-downloader
lein run -m fantasy-football-2015.yahoo-downloader

lein run -m fantasy-football-2015.aggregate-players
